name: autis
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Add by me
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_database: ^11.2.0
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6

  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  animated_notch_bottom_bar: ^1.0.3
  go_router: ^13.0.0
  flutter_screenutil: ^5.6.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  equatable: ^2.0.5
  provider: ^6.1.2
  enefty_icons: ^1.0.7
  shimmer: ^3.0.0
  uuid: ^4.5.1
  file_picker: ^6.1.1
  path_provider: ^2.1.5
  # flutter_svg: ^2.0.14
  get: ^4.6.6
  rxdart: ^0.28.0
  firebase_app_check: ^0.3.1+6
  intl: ^0.20.1
  connectivity_plus: ^6.1.0
  another_flushbar: ^1.12.30
  lottie: ^3.2.0
  async: ^2.11.0
  logger: ^2.5.0
  get_it: ^8.0.3
  flutter_secure_storage: ^9.2.2
  dartz: ^0.10.1
  flutter_dotenv: ^5.2.1
  # cloudinary packages
  image_picker: ^1.0.4
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0
  fluttertoast: ^8.2.12
  flutter_blurhash: ^0.8.2
  video_player: ^2.9.5
  iconsax: ^0.0.8
  chewie: ^1.10.0

  http: any
  crypto: any
dev_dependencies:
  launcher_name: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.4
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
launcher_name:
  default: "Autis'Guide"
# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/icon/icon.png"
#   remove_alpha_ios: true
flutter:
  generate: true
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/splash_image.png
    - assets/images/homebg.jpg
    - assets/images/image1.jpeg
    - assets/images/image2.jpeg
    - assets/images/n0.png
    - assets/images/n1.png
    - assets/images/n2.png
    - assets/images/n3.png

    - .env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
