// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDom6uJWEvLS_cetvVYe1JNgkZa1o-5JpA',
    appId: '1:619252910099:android:a96c63b98b08f868ad17e6',
    messagingSenderId: '619252910099',
    projectId: 'autis-62aef',
    databaseURL: 'https://autis-62aef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'autis-62aef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAO4F_Qg20utcWWd2zZR4Ko0530QGHq60',
    appId: '1:619252910099:ios:de3a3866645a7aabad17e6',
    messagingSenderId: '619252910099',
    projectId: 'autis-62aef',
    databaseURL: 'https://autis-62aef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'autis-62aef.firebasestorage.app',
    iosBundleId: 'com.example.autis',
  );

}